# Generated by Django 3.2.18 on 2023-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='teacher_id',
            field=models.CharField(max_length=10),
        ),
    ]
