# Generated by Django 4.2.2 on 2023-06-26 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_is_teacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
