# Generated by Django 4.2.3 on 2023-07-23 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_english_name", models.CharField(max_length=50)),
                (
                    "student_chinese_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("session", models.PositiveBigIntegerField()),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FreeSection",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iranian_time",
                    models.CharField(
                        choices=[
                            ("9:00 - 9:45", "9:00 - 9:45"),
                            ("10:00 - 10:45", "10:00 - 10:45"),
                            ("11:00 - 11:45", "11:00 - 11:45"),
                            ("12:00 - 12:45", "12:00 - 12:45"),
                            ("13:00 - 13:45", "13:00 - 13:45"),
                            ("14:00 - 14:45", "14:00 - 14:45"),
                            ("15:00 - 15:45", "15:00 - 15:45"),
                            ("16:00 - 16:45", "16:00 - 16:45"),
                            ("17:00 - 17:45", "17:00 - 17:45"),
                            ("18:00 - 18:45", "18:00 - 18:45"),
                            ("19:00 - 19:45", "19:00 - 19:45"),
                            ("20:00 - 20:45", "20:00 - 20:45"),
                            ("21:00 - 21:45", "21:00 - 21:45"),
                        ],
                        default="9:00 - 9:45",
                        max_length=50,
                    ),
                ),
                (
                    "chinese_time",
                    models.CharField(
                        choices=[
                            ("4:30 - 5:15", "4:30 - 5:15"),
                            ("5:30 - 6:15", "5:30 - 6:15"),
                            ("6:30 - 7:15", "6:30 - 7:15"),
                            ("7:30 - 8:15", "7:30 - 8:15"),
                            ("8:30 - 9:15", "8:30 - 9:15"),
                            ("9:30 - 10:15", "9:30 - 10:15"),
                            ("10:30 - 11:15", "10:30 - 11:15"),
                            ("11:30 - 12:15", "11:30 - 12:15"),
                            ("12:30 - 13:15", "12:30 - 13:15"),
                            ("13:30 - 14:15", "13:30 - 14:15"),
                            ("14:30 - 15:15", "14:30 - 15:15"),
                            ("15:30 - 16:15", "15:30 - 16:15"),
                            ("16:30 - 17:15", "16:30 - 17:15"),
                        ],
                        default="4:30 - 5:15",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        default="Sunday",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iranian_time",
                    models.CharField(
                        choices=[
                            ("9:00 - 9:45", "9:00 - 9:45"),
                            ("10:00 - 10:45", "10:00 - 10:45"),
                            ("11:00 - 11:45", "11:00 - 11:45"),
                            ("12:00 - 12:45", "12:00 - 12:45"),
                            ("13:00 - 13:45", "13:00 - 13:45"),
                            ("14:00 - 14:45", "14:00 - 14:45"),
                            ("15:00 - 15:45", "15:00 - 15:45"),
                            ("16:00 - 16:45", "16:00 - 16:45"),
                            ("17:00 - 17:45", "17:00 - 17:45"),
                            ("18:00 - 18:45", "18:00 - 18:45"),
                            ("19:00 - 19:45", "19:00 - 19:45"),
                            ("20:00 - 20:45", "20:00 - 20:45"),
                            ("21:00 - 21:45", "21:00 - 21:45"),
                        ],
                        default="9:00 - 9:45",
                        max_length=50,
                    ),
                ),
                (
                    "chinese_time",
                    models.CharField(
                        choices=[
                            ("4:30 - 5:15", "4:30 - 5:15"),
                            ("5:30 - 6:15", "5:30 - 6:15"),
                            ("6:30 - 7:15", "6:30 - 7:15"),
                            ("7:30 - 8:15", "7:30 - 8:15"),
                            ("8:30 - 9:15", "8:30 - 9:15"),
                            ("9:30 - 10:15", "9:30 - 10:15"),
                            ("10:30 - 11:15", "10:30 - 11:15"),
                            ("11:30 - 12:15", "11:30 - 12:15"),
                            ("12:30 - 13:15", "12:30 - 13:15"),
                            ("13:30 - 14:15", "13:30 - 14:15"),
                            ("14:30 - 15:15", "14:30 - 15:15"),
                            ("15:30 - 16:15", "15:30 - 16:15"),
                            ("16:30 - 17:15", "16:30 - 17:15"),
                        ],
                        default="4:30 - 5:15",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        default="Sunday",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.section",
                    ),
                ),
                (
                    "section_class",
                    models.ManyToManyField(blank=True, to="timetable.class"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreeSectionTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.freesection",
                    ),
                ),
                (
                    "free_section_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.class",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
