# Generated by Django 4.2.3 on 2023-07-15 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeSection",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iranian_time",
                    models.CharField(
                        choices=[
                            ("9:00 - 9:45", "9:00 - 9:45"),
                            ("10:00 - 10:45", "10:00 - 10:45"),
                            ("11:00 - 11:45", "11:00 - 11:45"),
                            ("12:00 - 12:45", "12:00 - 12:45"),
                            ("13:00 - 13:45", "13:00 - 13:45"),
                            ("14:00 - 14:45", "14:00 - 14:45"),
                            ("15:00 - 15:45", "15:00 - 15:45"),
                            ("16:00 - 16:45", "16:00 - 16:45"),
                            ("17:00 - 17:45", "17:00 - 17:45"),
                            ("18:00 - 18:45", "18:00 - 18:45"),
                            ("19:00 - 19:45", "19:00 - 19:45"),
                            ("20:00 - 20:45", "20:00 - 20:45"),
                            ("21:00 - 21:45", "21:00 - 21:45"),
                        ],
                        default="9:00 - 9:45",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        default="Sunday",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "iranian_time",
                    models.CharField(
                        choices=[
                            ("9:00 - 9:45", "9:00 - 9:45"),
                            ("10:00 - 10:45", "10:00 - 10:45"),
                            ("11:00 - 11:45", "11:00 - 11:45"),
                            ("12:00 - 12:45", "12:00 - 12:45"),
                            ("13:00 - 13:45", "13:00 - 13:45"),
                            ("14:00 - 14:45", "14:00 - 14:45"),
                            ("15:00 - 15:45", "15:00 - 15:45"),
                            ("16:00 - 16:45", "16:00 - 16:45"),
                            ("17:00 - 17:45", "17:00 - 17:45"),
                            ("18:00 - 18:45", "18:00 - 18:45"),
                            ("19:00 - 19:45", "19:00 - 19:45"),
                            ("20:00 - 20:45", "20:00 - 20:45"),
                            ("21:00 - 21:45", "21:00 - 21:45"),
                        ],
                        default="9:00 - 9:45",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        default="Sunday",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.section",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreeSectionTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.freesection",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
