# Generated by Django 3.2.19 on 2023-06-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20230618_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingtime',
            name='tid',
            field=models.CharField(default=0, max_length=25, primary_key=True, serialize=False),
        ),
    ]
