# Generated by Django 4.2.3 on 2023-07-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0003_alter_freesectionteacher_free_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freesectionteacher",
            name="free_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.section",
            ),
        ),
    ]
