# Generated by Django 4.2.3 on 2023-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_alter_freesectionteacher_free_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freesectionteacher",
            name="free_section_class",
        ),
        migrations.AddField(
            model_name="freesectionteacher",
            name="free_section_class",
            field=models.ManyToManyField(blank=True, to="timetable.class"),
        ),
    ]
