# Generated by Django 3.2.19 on 2023-06-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_teachingtime_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='teaching_time',
        ),
        migrations.AddField(
            model_name='section',
            name='chinese_time',
            field=models.CharField(choices=[('4:30 - 5:15', '4:30 - 5:15'), ('5:30 - 6:15', '5:30 - 6:15'), ('6:30 - 7:15', '6:30 - 7:15'), ('7:30 - 8:15', '7:30 - 8:15'), ('8:30 - 9:15', '8:30 - 9:15'), ('9:30 - 10:15', '9:30 - 10:15'), ('10:30 - 11:15', '10:30 - 11:15'), ('11:30 - 12:15', '11:30 - 12:15'), ('12:30 - 13:15', '12:30 - 13:15'), ('13:30 - 14:15', '13:30 - 14:15'), ('14:30 - 15:15', '14:30 - 15:15'), ('16:30 - 17:15', '16:30 - 17:15')], default='4:30 - 5:15', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=15),
        ),
        migrations.AddField(
            model_name='section',
            name='iranian_time',
            field=models.CharField(choices=[('9:00 - 9:45', '9:00 - 9:45'), ('10:00 - 10:45', '10:00 - 10:45'), ('11:00 - 11:45', '11:00 - 11:45'), ('12:00 - 12:45', '12:00 - 12:45'), ('13:00 - 13:45', '13:00 - 13:45'), ('14:00 - 14:45', '14:00 - 14:45'), ('15:00 - 15:45', '15:00 - 15:45'), ('16:00 - 16:45', '16:00 - 16:45'), ('17:00 - 17:45', '17:00 - 17:45'), ('18:00 - 18:45', '18:00 - 18:45'), ('19:00 - 19:45', '19:00 - 19:45'), ('20:00 - 20:45', '20:00 - 20:45'), ('21:00 - 21:45', '21:00 - 21:45')], default='9:00 - 9:45', max_length=50),
        ),
        migrations.DeleteModel(
            name='TeachingTime',
        ),
    ]
