# Generated by Django 4.2.3 on 2023-07-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0005_alter_freesection_chinese_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionteacher",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="timetable.section"
            ),
        ),
    ]
