# Generated by Django 4.2.3 on 2023-07-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0005_remove_freesectionteacher_free_section_class_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freesectionteacher",
            name="free_section_class",
        ),
        migrations.RemoveField(
            model_name="sectionteacher",
            name="section_class",
        ),
        migrations.AddField(
            model_name="freesectionteacher",
            name="free_section_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.class",
            ),
        ),
        migrations.AddField(
            model_name="sectionteacher",
            name="section_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.class",
            ),
        ),
    ]
