# Generated by Django 3.2.18 on 2023-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_section_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
