# Generated by Django 3.2.18 on 2023-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_freesectionteacher_free_section_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeSection',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='student_english_name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='student_chinese_name',
        ),
        migrations.AddField(
            model_name='section',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=15),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(default='2023', max_length=15),
        ),
    ]
