# Generated by Django 4.2.3 on 2023-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0007_alter_sectionteacher_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_english_name", models.CharField(max_length=50)),
                (
                    "student_chinese_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("session", models.PositiveBigIntegerField()),
            ],
        ),
    ]
