# Generated by Django 3.2.18 on 2023-08-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20230730_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freesectionteacher',
            old_name='free_section',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='freesectionteacher',
            old_name='free_section_class',
            new_name='section_class',
        ),
    ]
