# Generated by Django 4.2.3 on 2023-07-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0009_remove_freesectionteacher_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="platform",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
