# Generated by Django 3.2.18 on 2023-06-24 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0011_alter_section_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='teacher',
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
