# Generated by Django 3.2.18 on 2023-06-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20230624_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
