# Generated by Django 4.2.2 on 2023-07-05 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0013_rename_teacher_section_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="chinese_time",
        ),
        migrations.AlterField(
            model_name="section",
            name="teachers",
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
